### ISSUE TITLE
Please give some additional people commit access

### ISSUE THREAD

**Issue by tarsius** [hober/planet.emacsen.org#77]
Thanks for maintaining the planet. Unfortunately it seems like you don't have enough time to give it the attention it deserves and so pull requests can go unmerged for months, even without any comments.

I would like to suggest that you give some additional people commit access. These should people who are on Github a lot and have a reputation of being responsive. I suggest, if he agrees to do it, @purcell, and am volunteering myself too.

**Comment by tarsius** [comment]
@jwiegley @sachac, if I remember correctly, the two of you have commit access for this repository? If so, then please consider this offer (and while/before things get settled, also merge #76).

**Comment by sachac** [comment]
Oh, I don't have commit access to this, but that might be a good idea (plus figuring out some way to deploy to planet.emacsen.org in a way that @hober trusts?). @hober is probably busy due to real-life awesomeness, but I'll ping https://twitter.com/hober and see if she responds.

**Comment by jwiegley** [comment]
I don't have access either.

**Comment by tarsius** [comment]
Thanks Sacha.

And well, I didn't remember correctly ;-)

**Comment by gavenkoa** [comment]
It is better to move Planet to another place. I see requests from a summer to include feed.

One place of Emacs effort is https://melpa.org/ This server have large power and it is not too difficult to serve some static files. Especially taking in account that melpa is driven by GitHub pull requests like planet recently...

But there can be other suitable places...

**Comment by gavenkoa** [comment]
I can't understand the relation between http://www.planetplanet.org/ and http://intertwingly.net/code/venus/

**Comment by gavenkoa** [comment]
Oh I see: *Planet Venus is a refactoring of Planet*. But Planet Venus is linked to original mail list for discussion...

**Comment by mathiasdahl** [comment]
Has this been sorted out yet?

**Comment by tarsius** [comment]
No

**Comment by tarsius** [comment]
Considering that the maintainer still hasn't replied, I think it would be a *really* good idea to add some more maintainers.

**Comment by hober** [comment]
The site doesn't require much in the way of maintenance and I give it the amount of attention that I need to. I'm sorry that you aren't satisfied with the level of maintenance. Fortunately it's quite easy to run a site like this yourself. Give it a try if you'd like.
