### ISSUE TITLE
Make post date visible.

### ISSUE THREAD

**Issue by gavenkoa** [hober/planet.emacsen.org#78]
*Post date* is shown after *post title* and *author name*. If prior strings are too long the date of the post publication is lost behind area of `<pre class="mode-line">`.

On some other Planets *post title* and *author name* limited to certain characters. Another way is to put date in front of *mode-line*.

**Comment by hober** [comment]
People mostly consume the site with RSS readers; the utility of the web view is secondary. That said, if you'd like to take a stab at this change, I'd be happy to accept a pull request.
