### ISSUE TITLE
emacs.cafe missing from planet.emacsen.org

### ISSUE THREAD

**Issue by NicolasPetton** [hober/planet.emacsen.org#81]
I don't know if there was something else to do other than PR #80, but http://planet.emacsen.org doesn't have emacs.cafe yet.

**Comment by mathiasdahl** [comment]
I don't think anything else is needed from you. I don't remember how long time it took before I saw my blog entries in there when mine was added. Did you add any blog entries after your PR was merged? Not sure if old ones are automatically added or not. Ping @hober

**Comment by hober** [comment]
I've updated the server with the latest from GitHub. Thanks for the patch!
