### ISSUE TITLE
Wisdom and Wonder Blog Pull Quit Working

### ISSUE THREAD

**Issue by grettke** [hober/planet.emacsen.org#83]
Good morning,

Long time fan and first time caller here!

The feed from blog going into Planet Emacsen broke right around the time that
one of the posts had a character Unicode title. I fixed it but my feed still
isn&rsquo;t getting pulled. You changed it to HTTP and that helped for a while but
then quit working.

From what I can see [W3C](https://validator.w3.org/feed/check.cgi?url=) and [FeedValidator](http://www.feedvalidator.org/check.cgi) are
happy with [the feed](https://www.wisdomandwonder.com/tag/emacs/feed). Is Planet Emacsen happy with that feed?

-   How do thing look on your end?
-   What can I do narrow things down on my end?

**Comment by hober** [comment]
I merged your pull request. Let me know if things still don't work!

**Comment by grettke** [comment]
@hober Will do. Thank you and have a great day.
